WebApp/Models/ErrorViewModel.cs
using System;

namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApp/Models/Wexnet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Models
{
    public class Wexnet
    {
        static int idCount = 0;
        public static List<Wexnet> DBWexnet = new List<Wexnet>();
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage ="Enter Hestighet")]
        public string Hestighet { get; set; }
        [Required(ErrorMessage = "Enter RingNamn")]
        public string RingNamn { get; set; }
        [Required(ErrorMessage = "Enter IP Adress Dist A")]
        [RegularExpression(@"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")]
        public string IPAdressDistA { get; set; }
        [Required(ErrorMessage = "Enter Port Dist A")]
        public string PortDistA { get; set; }
        [Required(ErrorMessage = "Enter IP Adress Dist B")]
        [RegularExpression(@"^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$")]
        public string IPAdressDistB { get; set; }
        [Required(ErrorMessage = "Enter Port Dist B")]
        public string PortDistB { get; set; }
        public Wexnet()
        {
            Id = idCount++;
            if(Id ==0)
            {
                Wexnet.DBWexnet.Add(new Wexnet { Hestighet = "10", RingNamn = "wex1234", IPAdressDistA = "1.1.1.2", PortDistA = "1", IPAdressDistB = "2.2.2.3", PortDistB = "1" });
                Wexnet.DBWexnet.Add(new Wexnet { Hestighet = "1", RingNamn = "wex1080", IPAdressDistA = "10.105.4.116", PortDistA = "7", IPAdressDistB = "10.105.4.135", PortDistB = "29" });
                
            }

        }
    }
}

WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            Wexnet me= new Wexnet();
            return View(Wexnet.DBWexnet);
        }
       [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind(include: "Id,Hestighet,RingNamn,IPAdressDistA,PortDistA,IPAdressDistB,PortDistB")]Wexnet wexnet)
        {
            if(ModelState.IsValid)
            {
                Wexnet.DBWexnet.Add(wexnet);
                return RedirectToAction("Index");
            }
            return View(wexnet);
        }
        public IActionResult Delete(int id)
        {
            Wexnet wexnet = Wexnet.DBWexnet.SingleOrDefault(m => m.Id == id);
            Wexnet.DBWexnet.Remove(wexnet);
            return RedirectToAction("Index");
        }
        
        
       
        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApp/Controllers/WexnetController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Newtonsoft.Json;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class WexnetController : Controller
    {
        

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Wexnet wexnet)
        {
            string hestighet;
            hestighet = wexnet.Hestighet;

            if (hestighet == "1")
            {
                return Content($"Python3 config-access-ring.py {wexnet.RingNamn}  {wexnet.IPAdressDistA}  Gi0/0/0/{wexnet.PortDistA}  {wexnet.IPAdressDistB} Gi0/0/0/{wexnet.PortDistB}");
            }
            else
            {
                return Content($"Python3 config-gen_new_access_ring{wexnet.Hestighet}g.py  {wexnet.RingNamn} {wexnet.IPAdressDistA} Te0/0/0/{wexnet.PortDistA} {wexnet.IPAdressDistB} Te0/0/0/{wexnet.PortDistB}");
            }
        }

      public IActionResult File()
        {
            return View("File");
        }
        [HttpPost]
        public IActionResult GetFile()
        {
            
            return RedirectToAction("File");
        }
    }
}

WebApp/Views/Home/Create.cshtml
@using WebApp.Models
@model IEnumerable<Wexnet>

@{
    ViewBag.Title = "Create";
    //<script src="http://ajax.googleapis.com7ajax/libs/jquary/3.5.1/jquary.min.js"></script>
}
<style>
    * {
        box-sizing: border-box;
    }

    form {
        padding: 1em;
        background: #f9f9f9;
        border: 1px solid #c1c1c1;
        margin-top: 2rem;
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
        padding: 1em;
    }

        form input {
            margin-bottom: 1rem;
            background: #fff;
            border: 1px solid #9c9c9c;
        }

        form button {
            background: lightgrey;
            padding: 0.7em;
            border: 0;
        }

    h2 {
        text-align: left;
    }
</style>


<h2>WEXNET</h2>
<div class="row">

    <div class="col-lg-6 col-lg-offset-3 text-left">
        <section id="WEXNET">
            
                @using (Html.BeginForm("ShowData", "Wexnet", FormMethod.Post))
                {
                    var wexnet = new Wexnet();
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true);
                    <br />
                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.Hestighet, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(Model => wexnet.Hestighet, new List<SelectListItem>
                               {  new SelectListItem{Text = "1", Value= "1"},
                                   new SelectListItem{Text = "10",Value = "10"}}, "Please Select")
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.RingNamn, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(Model => wexnet.RingNamn)
                            @Html.ValidationMessageFor(Model => wexnet.RingNamn)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.IPAdressDistA, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(Model => wexnet.IPAdressDistA)
                            @Html.ValidationMessageFor(Model => wexnet.IPAdressDistA)

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.PortDistA, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(Model => wexnet.PortDistA, Enumerable.Range(1, 36).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { placeholder = Html.DisplayNameFor(Model => wexnet.PortDistA), @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.IPAdressDistB, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(Model => wexnet.IPAdressDistB)
                            @Html.ValidationMessageFor(Model => wexnet.IPAdressDistB)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(Model => wexnet.PortDistB, new { @class = "control-label col-md-2" })
                        <div class="col-md-6">
                            @Html.DropDownListFor(Model => wexnet.PortDistB, Enumerable.Range(1, 36).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { placeholder = Html.DisplayNameFor(Model => wexnet.PortDistB), @class = "form-control" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Submit" class="btn btn-default" />
                        </div>
                    </div>
                    <p>
                        @Html.ActionLink("Tillbaka till listen", "Index")
                    </p>

                 }
            
        </section>
    </div>
</div>

WebApp/Views/Home/Index.cshtml
@using WebApp.Models
@model IEnumerable<Wexnet>
@{
    ViewBag.Title = "Index";
}
<h2>WEXNET LIST</h2>
<p>
    @Html.ActionLink("Skapa nytt", "Create")
</p>


<table class="table table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Hestighet)</th>
            <th>@Html.DisplayNameFor(model => model.RingNamn)</th>
            <th>@Html.DisplayNameFor(model => model.IPAdressDistA)</th>
            <th>@Html.DisplayNameFor(model => model.PortDistA)</th>
            <th>@Html.DisplayNameFor(model => model.IPAdressDistB)</th>
            <th>@Html.DisplayNameFor(model => model.PortDistB)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Hestighet)</td>
                <td>@Html.DisplayFor(modelItem => item.RingNamn)</td>
                <td>@Html.DisplayFor(modelItem => item.IPAdressDistA)</td>
                <td>@Html.DisplayFor(modelItem => item.PortDistA)</td>
                <td>@Html.DisplayFor(modelItem => item.IPAdressDistB)</td>
                <td>@Html.DisplayFor(modelItem => item.PortDistB)</td>
                <td>@Html.ActionLink("Ta bort","Delete", new { id = item.Id})</td>
            </tr>
        }
    </tbody>
</table>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Wexnet" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wexnet" asp-action="Index">Home</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApp - Fakhara Imran<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/Views/Wexnet/File.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{ 
    ViewBag.Title = "File";
}
<div>
    <form asp-controller="wexnet" asp-action="GetFile" enctype="multipart/form-data"method="post">
        <button type="submit">Scripkt Kors</button>
    </form>
</div>

WebApp/Views/Wexnet/GetFile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewBag.Title = "GetFile";

}

WebApp/Views/Wexnet/Index.cshtml
@model WebApp.Models.Wexnet
@{
    ViewBag.Title = "Index";
    <script src="http://ajax.googleapis.com7ajax/libs/jquary/3.5.1/jquary.min.js"></script>
 }


<style>
    * {
        box-sizing: border-box;
    }

    form {
        padding: 1em;
        background: #f9f9f9;
        border: 1px solid #c1c1c1;
        margin-top: 2rem;
        max-width: 500px;
        margin-left: auto;
        margin-right: auto;
        padding: 1em;
    }

        form input {
            margin-bottom: 1rem;
            background: #fff;
            border: 1px solid #9c9c9c;
        }

        form button {
            background: lightgrey;
            padding: 0.7em;
            border: 0;
        }

    h2 {
        text-align: left;
    }
</style>


<h2>WEXNET</h2>

<div class="row">

    <div class="col-lg-6 col-lg-offset-3 text-left">
        <section id="WEXNET">

            @using (Html.BeginForm("Index", "Wexnet", FormMethod.Post))
            {
                var wexnet = new Wexnet();
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true);
                <br />
                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.Hestighet, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(Model => wexnet.Hestighet, new List<SelectListItem>
                           {  new SelectListItem{Text = "1", Value= "1"},
                               new SelectListItem{Text = "10",Value = "10"}}, "Please Select")
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.RingNamn, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(Model => wexnet.RingNamn)
                        @Html.ValidationMessageFor(Model => wexnet.RingNamn)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.IPAdressDistA, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(Model => wexnet.IPAdressDistA)
                        @Html.ValidationMessageFor(Model => wexnet.IPAdressDistA)

                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.PortDistA, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(Model => wexnet.PortDistA, Enumerable.Range(1, 36).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { placeholder = Html.DisplayNameFor(Model => wexnet.PortDistA), @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.IPAdressDistB, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(Model => wexnet.IPAdressDistB)
                        @Html.ValidationMessageFor(Model => wexnet.IPAdressDistB)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(Model => wexnet.PortDistB, new { @class = "control-label col-md-2" })
                    <div class="col-md-6">
                        @Html.DropDownListFor(Model => wexnet.PortDistB, Enumerable.Range(1, 36).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), new { placeholder = Html.DisplayNameFor(Model => wexnet.PortDistB), @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
             }
        </section>
    </div>
</div>